### ISSUE TITLE
By Friday the server is once again impossibly slow

### ISSUE THREAD

**Issue by kimballa** [burningmantech/ranger-ims-server#124]
There are lags of > 5 seconds per field. This system will clear out any updates you make during this interval. Meaning it takes over a minute to log a new incident. This is unusably slow.

**Comment by kimballa** [comment]
It loses about half the field updates. Changing rangers or incident types also is incredibly slow and glitchy again.

**Comment by kimballa** [comment]
some of the time it then sends several alert/messagebox/modals saying "Cannot apply edit" in a row when I try to move with any speed thru the fields

**Comment by kimballa** [comment]
also includes modals saying "Cannot load incident"

**Comment by wsanchez** [comment]
Not a scaling problem; demo server with 2016 data is not at all slow.

Again, I suspect, networking.

**Comment by corprew** [comment]
was afternoon shift lead on friday and was having network-specific problems using IMS from back in shift lead land.  i vote with @wsanchez.

**Comment by flwyd** [comment]
Since "occasionally terrible networking" is a known condition on the playa[1], I'd argue that IMS and Clubhouse should be designed for unreliable networks with high latency.

[1] I'd like to understand how the network connection between Operator workstations and the IMS server can be bad.  Is it not two ethernet cables and one switch?
I think someone mentioned that when using *.nv.burningman.org, requests have to go from HQ to the NOC and back, so maybe we need to specify IP addresses in bookmarks or something.

**Comment by kimballa** [comment]
Indeed. As a user, I honestly don't care why it's a problem. The system is slow enough that it's unusable in real time. This is a critical failure in a real time logging application.

I don't mean to be harsh, but this is the facts: this app induces rage in me when I'm crusty by the end of the week anyway, and to top it off, it just doesn't respond.

**Comment by wsanchez** [comment]
Be harsh all you want.  :-)

But as a developer, I care about what the appropriate fix is, and if networking between the server and the client machines *in the same building* is slow, then that's the problem to fix.  That's not a bug to track here, though.

We have other open tickets on adding more aggressive client-side caching (eg. more local/session storage) that may help here, but writing new data has to get to the server over the network.

**Comment by kimballa** [comment]
I think there are bugs at both levels.

* Yes, the network should be fixed
* _But_, we said the network would be fixed this year, and the app design doesn't support a high-latency connection. In production, the network isn't performant; and the experience was poor. Now we're saying "the network will be better next year" again. Is that something this app should bank on? I think that redundant levels of fault tolerance are necessary in an HA real-time application. 

I have to underscore: if this was the "ranger office" application as used in the HQ window, I wouldn't be making these complaints. It's ok for things to lag there. But when radios are going fast, it is incredibly unnerving to not be able to trust the software to record what I'm writing faithfully. This application use case demands a much tighter SLA and this needs to be delivered somehow.

Given that you claim the network was local-only, that makes one wonder: is it _really_ the network at fault? Or is something else going on?

When you say that the demo server loaded the 2016 data and performed fine, I believe you. After all, it's only about 1500 incidents; these should fit on a floppy disk or two. But is there possibly a memory or other resource leak associated with sustained usage?

That is, has this been tested in a test/simulation environment where for a one-week period, it's accessed in a typical r/w pattern 24/7, as it is on the playa? I can't help but observe that the performance noticeably degraded over the course of the week.  There may be resources like sockets, mem, etc. that are not being freed in the production environment which artificially throttle performance.

**Comment by wsanchez** [comment]
I'm aware of all of the above, thanks.

**Comment by hariboukis** [comment]
Fellow Nerds, Socrates;

Here is what I observed while working IT as well as Operator, IMS, and HQ Secret Clubhouse. 

At the beginning of the week, including pre-event, connectivity to both IMS and SC was spotty. As event week progressed, the problem frequency worsened but did not last as long, and for the most part solved itself without any intervention. 

Probable causes and possible fixes:

Initial Internet and IMS and SC connectivity issues were caused by inability of ORG DNS to respond in time. It does not matter if DNS is hosted or controlled by ORG or hosted on Playa or off.  I believe that high latency on ORG backbone caused DNS request timeouts and therefore failure for the individual browsers to resolve the IO assesses. 

Fix: Since we are assigns fixed IP addresses for both the IMS and SC servers, which we manually enter into each machine, there is NO reason to reference those servers with DNS, and therefore if we address by IP address, we remove the DNS-failure issue. 

The second problem which crept up on us later in the week was, I believe, caused by stuck keys on dusty keyboards flooding the servers with repeated requests. I directly observed enter keys getting stuck and killing the SC server. I had to restart it a couple of times to get it back up. 

Possible fixes:

1.  Purchase dust-proof keyboards. 
2.  Purchase new keyboards and affix a rubber membrane over the keys to prevent dust. 

We should get the keyboards no matter what. It is incredibly frustrating and painful (read workplace ergonomics) to use the existing keyboards.  We need them for HQ, ROC, and outposts. Probably 20 or so. 

3.  Add JavaScript to IMS and SC to prevent enter key flooding. 
4.  Add some PHP code to check for flooding. It won't prevent Apache/PHP flooding, but can trap too many access requests to MySQL, where I believe the problem lies with the slowness here. 

5.  Look at storage portion of each odroid. If not entirely running in RAM, is it a SD card? Can that card handle multiple access requests gracefully?  If not, consider replacing with a SSD. Sure, it will not fit in the small case, but can be duct-taped to the outside -or consider a larger case. Either way, SSDs are cheap and run cool. 

6. Are all tables in database optimally indexed?  If not, index them all. 


Faithfully submitted ...
Douglas C. Neidermier....

Oh, wait...,

Socrates


--------------------------------
Hari Boukis
Mobile: 925-351-7772
Mobile e-mail: Hari@Boukis.com
Fax: 925-956-7013
--------------------------------
Sent from mobile phone
--------------------------------


On Sep 13, 2016, at 4:18 AM, Trevor Stone <notifications@github.com> wrote:

Since "occasionally terrible networking" is a known condition on the playa[1], I'd argue that IMS and Clubhouse should be designed for unreliable networks with high latency.

[1] I'd like to understand how the network connection between Operator workstations and the IMS server can be bad. Is it not two ethernet cables and one switch?
I think someone mentioned that when using *.nv.burningman.org, requests have to go from HQ to the NOC and back, so maybe we need to specify IP addresses in bookmarks or something.
