### ISSUE TITLE
Reported issue of… stale sessions causing problems

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#218]
Report: "Browser would get confused when old tabs opened by a different user would get reused by the current user. Closing/restarting the browser would correct the issue."

**Comment by wsanchez** [comment]
Next step here is to see if we can reproduce this or something similar.

**Comment by srabraham** [comment]
The issue is still present, and I see it pretty often after restarting my local IMS server. I'm fairly sure the problem is that a stale TWISTED_SESSION value can continue being used even after logging in via a new tab, and that leads to the issue.

https://github.com/burningmantech/ranger-ims-server/issues/1363

**Comment by srabraham** [comment]
should be fixed by https://github.com/burningmantech/ranger-ims-server/pull/1456
