### ISSUE TITLE
Show IMS number and "create incident" button on Field Report page

### ISSUE THREAD

**Issue by virtual256** [burningmantech/ranger-ims-server#372]
Frequently, experienced Rangers will stop by the Operator shack to get the relevant IMS number for their Field Incident Report.  As is, this will usually get entered into the subject line.  Adding a dedicated place for this (and possibly a note to stop by the Operator shack) will help to streamline the process of attaching FIRs to IMS entries.

**Comment by prqpn** [comment]
OODs have also requested the ability to have a new Incident be created upon submitting a (Field) Incident Report for which it is known a corresponding Incident does not already exist. (OTDB 2023 #234; from OOD AAR).

**Comment by srabraham** [comment]
I'm going to take a shot at @prqpn's request

**Comment by srabraham** [comment]
OK, so here's my plan: we'll create a new non-editable "IMS #" field on the Field Report page. If there's not an IMS # already for the FR, then we'll show a button to let the user create one. We'll only show the button if the user has writeIncidents permissions.

While I'm in here, I'd also like the make the FR instructions collapsible, since they're very long and noisy for operators. We can have the instructions default to being visible by default, but hidden for people with writeIncidents permissions.

**Comment by kimballa** [comment]
Thanks Abraham! 

Just to double check where you're going with this:

- There will be a view-only `IMS #` field on the "New/View Field Report" page.
- When a user is creating a new field report, this will be blank. If an operator has said "btw, Bucket, when you create your field report, reference `IMS 123`", they'll still just type `123` in the `title` field as is current best-practice.
- If the field report is already attached to an incident, and you're viewing a field report (rather than creating a new one), the `IMS #` field will be populated with the incident it is attached to. (And, presumably, this is a link that lets them go to the incident in question?)
- If the field report is *not* attached to an incident, _and_ the user has `writeIncidents` permission, the empty `IMS #` field is replaced with a button to `Create new incident`.
- When clicked, that button will:
  - Create a new Incident,
  - Set the Incident title to the title from the field report,
  - Add the author of the field report to the `Rangers` list,
  - And attach the field report to the Incident in question.
 
Is my understanding correct? 

+1 to collapsable instructions (and hiding them intelligently based on user role)

fwiw, I think the original request from @virtual256 was to create a separate field for `intended incident #` where the field report author could enter the number given to them verbally by the Operator (rather than an `IMS #` field that shows the actually _bound_ incident post-attachment); presumably that could lead to the following UX improvements:

- The "attach field report" drop down in an Incident display would put any field reports with matching `intended incident #` at the top of the dropdown list
- The Incident display page could have a banner or mid-screen toast or other highlight saying something like "There are field reports for this incident" with a button to quickly preview the field report(s) in question and/or directly attach them to the incident.
- When viewing the field report, someone with `writeIncidents` permission could have a button that says "Attach directly" which would attach the field report to the intended incident.

To be clear, I think the improvements you are proposing (i.e., the first bulleted list above) are helpful and I am +1 to both. But they are slightly different from what I understood the spirit of the request to be. 

I might suggest that these might be separate feature improvements / issue #'s here.

**Comment by srabraham** [comment]
Hey @kimballa , your understanding of my next steps (which are now in a PR) are almost totally correct. The one correction (relevant to your text afterward too) is that I provide the linkified incident number even for people without readIncidents. They can click on it and get a "permission denied", but that's consistent with the rest of the system (indeed, we show incident numbers in the Field Reports table page, even for people without readIncidents).

I see what you mean about @virtual256 's ask versus my suggestion. Hmmm...I'll ponder that. Let's discuss it when we talk soon

Sidebar: the "attached incident reports" dropdown is now easier to work with, so that's cool, and makes the Operator's situation a fair bit better: https://github.com/burningmantech/ranger-ims-server/issues/1319

**Comment by srabraham** [comment]
I think I have this in a pretty good state now. It pretty much does what @prqpn requested, in that it strongly guides the user into adding an IMS number into the summary. https://github.com/burningmantech/ranger-ims-server/pull/1449

Here's what the page looked like a few months ago:

<img width="786" alt="image" src="https://github.com/user-attachments/assets/7a984ea9-42ba-4003-89ca-663a87f9efb5" />

and here's what it looks like now, for a new Field Report. Note the placeholder text:

<img width="834" alt="image" src="https://github.com/user-attachments/assets/a40313c2-3221-4b15-a25c-e8dba614ba33" />

once you've saved a summary, the FR is assigned a number, and then the "Create new incident" button shows up, provided that the user has writeIncidents permission.

<img width="840" alt="image" src="https://github.com/user-attachments/assets/2763873b-3a38-4a91-9aac-e56b597245bf" />
