### ISSUE TITLE
References to numbers would benefit from a prefix

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#76]
References to numbers would benefit from a prefix so as to distinguish incident number across events and from incident report numbers, as each has a separate namespace.

One option is that incident numbers are prefixed with the event ID (eg. `2016-123`) and incident reports with `IR-` (eg. `IR-123`).

Downside to event ID method is that an event ID can have spaces which might be confusing if co-mingled with other text (eg. `Burning Man 2016-123`).

**Comment by wsanchez** [comment]
I'm thinking another option is that we don't display numbers for incident reports and refer to them by summary only.

**Comment by plapsley** [comment]
It is another option but I think this is a mistake.

Generally speaking, every item needs a unique identifier, both so you can easily and unambiguously refer to it, and also so you don’t get the resulting confusion from “Oh, you know, it was the incident report that Bayou submitted on Tuesday.”  “Right, Bayou submitted three incident reports on Tuesday.”  “No, but the one for horse cock.”  “Right, Bayou submitted two for horse cock on Tuesday.”

Vs. “It’s in incident report IR-0057.”

One thing you could do would be to be to assign some random prefix.  Look at what UPS has done with its “1Z” prefix for all UPS tracking numbers.  It’s at the point now if you see something starting with “1Z” you know it’s UPS.

I suggest “0x” as the prefix, just to fuck with people.  :-)

phil

**Comment by rangerfortress** [comment]
Ha!  I just must chime in.  0x would be classic, we'd tell non-programmers
it's a hug and a kiss for the dirt ranger who handled the incident.

Fortress

**Comment by wsanchez** [comment]
I disagree with @plapsley here.  I think that you you call someone about an incident report, that they are less likely to remember the number than the subject of the report.

If we add a summary field to incident reports, then I think that a label comprised of the author and summary is a better handle to a report than a number.

**Comment by corprew** [comment]
I think one advantage to assigning numerical identifiers to reports, though, is that a lot of incident reports have abstracting facets that we don't want to put on the radio because they contain PII.  

"Operator, Khaki.  could you pull up the incident report 'Hubcap-Sexual-Assault-Campname' and let me know ......"

"Khaki, OOD.  I need to talk to you about 'Hubcap-Domestic-Violence-Description'"

A combination of the two, with the author's callsign and a number like "IR-hubcap-####" would enable us to refer to things like "hubcap's incident report from last night" and be hopefully fairly clear. 

Unless I'm misunderstanding how you want to summarize incidents, of course.

**Comment by wsanchez** [comment]
@corprew: My "vision" for this is that we don't generally talk about incident reports as a thing so much as something that gets created and merged into an incident.  So you'd more likely be talking about Hubcap's report in incident 234.

**Comment by wsanchez** [comment]
I've changed how incident reports are referred to in the UI to `author: summary…`

64a4a880a9dbe4a33a4377b326917f587a699ef3
