### ISSUE TITLE
Add day of week to create date in dispatch queue

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#79]
@plapsley requests:

For dates at Burning Man you need both day of week (Mon, Tue, etc.) as well as month/day, since “Mon” binds more tightly in the human brain than “8/29” and people leave their calendars behind.

So …. two suggestions:

1. In IMS, whenever there’s a date stamp, suggest adding day of week to it.  E.g. `Thu 8/29` instead of `8/29`.

2. Because days of week are not unique since we’re out there for more than a week, I’ve been thinking about changing some of the Clubhouse reports to use a “-“ or “+” suffix to indicate pre- or post event (and no suffix if it’s during the event).

So if I see “Thu-“ I know it’s Thursday pre-event, where “Tue+” means the day after labor day.

**Comment by wsanchez** [comment]
FWIW, I don't like #2.

In the Mac app, I has a single letter prefix (S M T W R F N) to keep the columns narrow.  Three letter prefix is probably better because most people don't know what R and N are.

**Comment by rangerlibrarian** [comment]
+1 for the three letter day option, and for Phil's suggestion #1.

For pre & post, can we say "pre-Thu" or "post-Tue"?

**Comment by corprew** [comment]
+1 (1) / -1 (2)

> For pre & post, can we say "pre-Thu" or "post-Tue"?

"Thu Pre" & "Thu Post" aren't that different from Thu 8/## and Thu 9/## rendering surface-wise.

**Comment by plapsley** [comment]
Right, but they’re vastly different in terms of immediacy of comprehension, especially after a few days on playa, or several years post event.

If I tell you something happened Thursday pre-event in 2014, you know exactly when it happened in terms of locating it in your mental date space.  If I tell you it happened on Thu 8/27/14, you have no idea if that is pre or during (though you can guess it’s not post since it’s not in September).

The spatial equivalent telling you “It’s at 51st and Telegraph” vs. giving you a lat-long coordinate.  One has immediate intuitive meaning if you know the area.  The other is just a string of numbers.

phil

**Comment by wsanchez** [comment]
This is controlled by `shortFormatDate` in `ims.js`.

**Comment by wsanchez** [comment]
`moment.js` can do two-letter day of week, so gonna use that because less wide but should still be clear: 719679c4c44950855e90126115764b3412e56a45

**Comment by wsanchez** [comment]
Plus 18d8b5bb0522158d2a5b466088125e86e67ef004 to add a word break, so that the table renderer can split the date into two lines in a place that makes sense.
